# Generated by Django 5.2.8 on 2025-11-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
